# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSY7EB4yQkusia3G8D4v-Gg7h6E_0c39
"""

PLANS = {
    "Basic": {
        "can_stream": True,
        "can_download": False,
        "has_SD": True,
        "has_HD": False,
        "has_UHD": False,
        "num_of_devices": 1,
        "content": "3rd party movie only",
        "price": 120_000
    },
    "Standard": {
        "can_stream": True,
        "can_download": True,
        "has_SD": True,
        "has_HD": True,
        "has_UHD": False,
        "num_of_devices": 2,
        "content": "Basic + Sports",
        "price": 160_000
    },
    "Premium": {
        "can_stream": True,
        "can_download": True,
        "has_SD": True,
        "has_HD": True,
        "has_UHD": True,
        "num_of_devices": 4,
        "content": "All incl. Originals",
        "price": 200_000
    }
}

USER_DATA = {
    "andi": {"active_plan": "Basic", "duration": 14},
    "budi": {"active_plan": "Standard", "duration": 6},
    "citra": {"active_plan": "Premium", "duration": 18}
}

class Pacflix:
    def __init__(self):
        self.plans = PLANS
        self.users = USER_DATA

    def show_all_plans(self):
        print("=== All Available Plans ===")
        for name, features in self.plans.items():
            print(f"\n{name} Plan:")
            for k, v in features.items():
                print(f"  {k}: {v}")
            print("-" * 30)

    def check_user_plan(self, username):
        user = self.users.get(username.lower())
        if not user:
            return f"User '{username}' tidak ditemukan."
        return f"User '{username}' menggunakan plan: {user['active_plan']} (durasi: {user['duration']} bulan)"

    def upgrade_plan(self, username, new_plan):
        username = username.lower()
        user = self.users.get(username)
        if not user:
            return f"User '{username}' tidak ditemukan."

        current_plan = user["active_plan"]
        duration = user["duration"]
        plan_order = ["Basic", "Standard", "Premium"]

        if new_plan not in self.plans:
            return f"Plan {new_plan} tidak tersedia."

        if plan_order.index(new_plan) <= plan_order.index(current_plan):
            return "Upgrade gagal: tidak boleh downgrade atau plan sama."

        original_price = self.plans[new_plan]["price"]
        final_price = original_price

        if duration > 12:
            final_price *= 0.95

        # Update user data
        user["active_plan"] = new_plan

        return f"Biaya upgrade ke {new_plan} untuk {username}: Rp {int(final_price)}"

    def register_new_user(self, username, plan, referral_code=None):
        if plan not in self.plans:
            return f"Plan {plan} tidak tersedia."

        price = self.plans[plan]["price"]
        if referral_code:
            price *= 0.96

        self.users[username.lower()] = {"active_plan": plan, "duration": 0}
        return f"Biaya pendaftaran user baru {username}: Rp {int(price)}"

# ========================
# Interaktif
def main():
    app = Pacflix()
    while True:
        print("\n=== Selamat datang di Pacflix CLI ===")
        username = input("Masukkan username Anda (atau ketik 'exit' untuk keluar): ").strip().lower()
        if username == "exit":
            print("Terima kasih telah menggunakan Pacflix.")
            break

        print("\nPilih aksi:")
        print("1. Lihat semua plan")
        print("2. Lihat plan saya")
        print("3. Upgrade plan")
        print("4. Daftar sebagai user baru (pakai referral code)")
        print("5. Kembali ke input username")

        pilihan = input("Masukkan pilihan (1-5): ").strip()

        if pilihan == "1":
            app.show_all_plans()

        elif pilihan == "2":
            print(app.check_user_plan(username))

        elif pilihan == "3":
            new_plan = input("Masukkan plan baru (Standard/Premium): ").strip()
            print(app.upgrade_plan(username, new_plan))

        elif pilihan == "4":
            plan = input("Pilih plan (Basic/Standard/Premium): ").strip()
            referral = input("Masukkan referral code (atau tekan Enter jika tidak ada): ").strip()
            referral = referral if referral else None
            print(app.register_new_user(username, plan, referral))

        elif pilihan == "5":
            continue  # balik ke input username

        else:
            print("Pilihan tidak valid. Coba lagi.")

if __name__ == "__main__":
    main()